# Generated by Django 4.2.6 on 2023-10-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_students', '0003_alter_booking_date_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transportation_choice',
            field=models.CharField(blank=True, choices=[('pickup', 'Pick-up'), ('lorry', 'Lorry')], max_length=100, null=True),
        ),
    ]
