# Generated by Django 4.2.6 on 2023-11-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_students', '0005_booking_end_datetime_booking_start_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='end_datetime',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='start_datetime',
            new_name='start_date',
        ),
    ]
