# Generated by Django 4.2.6 on 2023-11-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_students', '0006_rename_end_datetime_booking_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
