# Generated by Django 4.2.6 on 2023-11-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_students', '0009_alter_booking_rate_alter_booking_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
