# Generated by Django 4.2.6 on 2023-11-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_students', '0010_alter_booking_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
