# Generated by Django 4.2.6 on 2023-11-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_students', '0011_alter_booking_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
