# Generated by Django 4.2.6 on 2023-11-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_students', '0012_alter_booking_rate_alter_booking_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='school',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
