# Generated by Django 4.2.6 on 2023-11-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_students', '0017_alter_booking_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='county',
        ),
    ]
