# Generated by Django 4.2.6 on 2023-11-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_students', '0020_lnmonline_alter_booking_phonenumber_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
