# Generated by Django 4.2.6 on 2023-11-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_students', '0021_alter_booking_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.IntegerField(),
        ),
    ]
