# Generated by Django 4.2.6 on 2023-12-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_students', '0022_alter_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
