# Generated by Django 4.2.6 on 2023-11-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0002_lnmonline_amount_lnmonline_balance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LNMOnline',
        ),
    ]
