# Generated by Django 4.2.6 on 2023-12-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LNMOnline',
        ),
    ]
