"""
Django settings for storagesystem project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a7%nbm0-=wnoc(_%e1qlg-=g31&%2(7zg#=ynhxxw-_bo=p$ud'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['yourdomain.com','localhost','a45c-197-232-90-116.ngrok-free.app']
#ALLOWED_HOSTS = ['yourdomain.com', 'localhost','e7ae-197-232-90-116.ngrok-free.app']
ALLOWED_HOSTS=[]

AUTH_USER_MODEL='authentications.CustomUser'


INSTALLED_APPS = [
    

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    'bootstrap4',
    'django_admin_logs',
    'django_filters',
    'rest_framework',

    'authentications',
    'dashboard_students',
    'dashboard_facility',
    'mpesa',
]




#Allows a superuser to delete logs
DJANGO_ADMIN_LOGS_DELETABLE = True
#View the logs in admin page
DJANGO_ADMIN_LOGS_ENABLED = True


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_auto_logout.middleware.auto_logout',#django auto logout(1)
]

ROOT_URLCONF = 'storagesystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_auto_logout.context_processors.auto_logout_client',#django auto logout(2)

            ],
        },
    },
]

WSGI_APPLICATION = 'storagesystem.wsgi.application'




# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
   'default': {
        'ENGINE': 'django.db.backends.sqlite3',
       'NAME': BASE_DIR / 'db.sqlite3',
    }
}

'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Storage',
        'USER': 'postgres',
        'PASSWORD': 'Akisa_001',
        'HOST': 'localhost',
        'PORT': '5433',
    }
}'''

'''DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.mysql',
       'NAME' : 'Storage',
       'USER': 'root',
       'PASSWORD': '',
       'HOST': 'localhost',
       'PORT': '3306', 
    
    }
}'''

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'UTC'  default that is supposed to be
TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS =[os.path.join(BASE_DIR, 'static')]
STATIC_ROOT=os.path.join(BASE_DIR, 'staticfiles')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
        # Other permission classes...
    ],
    # Other Django REST Framework settings...
}

#used in going live
#CSRF_TRUSTED_ORIGINS = ['https://d02c-197-232-90-116.ngrok-free.app']
#CSRF_TRUSTED_ORIGINS = ['https://a45c-197-232-90-116.ngrok-free.app']




# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTO_LOGOUT = {'IDLE_TIME':1800,'REDIRECT_TO_LOGIN_IMMEDIATELY':True, 
               'MESSAGE':'The session has expired.please login again to continue.'
               }

CRISPY_TEMPLATE_PACK = 'bootstrap5'

#smtp configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'storagefacilty617@gmail.com'
#EMAIL_HOST_PASSWORD ='sqkhenasymhsmrzc'
EMAIL_HOST_PASSWORD = 'nfnksilyqilujwpg'


