# Generated by Django 4.2.6 on 2023-10-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0004_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
