# Generated by Django 4.2.6 on 2023-10-31 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0005_alter_customuser_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storageprovider',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='storageprovider',
            old_name='name',
            new_name='staff_no',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='phone',
            new_name='phone_nummber',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
